import "@/styles/globals.css";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { Providers } from "./components/providers/Providers";
import { cn } from "./lib/utils";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  children: ReactNode;
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html
      lang="en"
      className={cn("bg-white text-slate-900 antialiased", inter.className)}
    >
      <body className="min-h-screen bg-slate-50 dark:bg-slate-900 antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
